### ISSUE TITLE
Astar Native Wallet Solution

### ISSUE THREAD

**Issue by fiexer** [AstarNetwork/AstarBounties#1]
## Astar Native Wallet Solution

**Difficulty: high**

### Description

Build a wallet that can manage various assets and view staking rewards from a single interface that is easy to use. Astar Network supports three types of accounts; the native SS58 account, EVM H160 account, and ECDSA custom signature accounts. Currently, there is no single solution that allows the user to use all types of accounts from a single wallet, and when they want to sign a native transaction or an EVM transaction. they have to switch wallets.

### Acceptance Criteria

- Create a browser extension that allows the user to manage assets for both the EVM account and native account at the same time.
- Users should be able to view and transfer their NFTs and ERC20 tokens.
- Other dApps can use this wallet to manage various accounts types.
- Supports ERC1155 and PSP1155 assets.

### Reward tiers

Up to $10,000

- Contribution to the Astar ecosystem (25%)
- Originality, Creativity, and Innovation (25%)
- Technical Difficulty (25%)
- User Experience (25%)

## Rules
1. You can submit your solution by opening a PR in this repo. Please include a readme file with the following:
    - Project title
    - Project description (minimum 150 words)
    - Contact information (Telegram handle or email)
    - Name of bounty you participated
    - Provide a way to access the project for judging and testing by including all links
    - Must have an open-source license
    - A video explaining your submission
2. All Submission materials must be in English
3. Bounty is paid in USDC on the Astar network

## Resources
- Official documentation: [Here](https://docs.astar.network/)
- Network details: [Here](https://docs.astar.network/integration/network-details)
- All about dApp staking: [Here](https://docs.astar.network/dapp-staking/introduction)
- Example of AsterBase: [Here](https://docs.astar.network/dapp-staking/for-developers/astarbase)
- Using precompiles: [Here](https://docs.astar.network/dapp-staking/for-developers/precompiles)
- Developer hack support: [Join here](https://t.me/AstarHack)

Happy hacking!

**Comment by TheGreatAxios** [comment]
@fiexer Is a mobile wallet an acceptable solution for this bounty? Additionally, can it be closed source temporarily as it is under heavy active development?
