### ISSUE TITLE
PSP34 NFT Minting Site - $3000

### ISSUE THREAD

**Issue by newnewsms** [AstarNetwork/AstarBounties#13]
## **PSP34 NFT Minting Site**

Difficulty: Low

Blockchain knowledge: Low

Frontend knowledge: Low

**Description**

Build a dApp for non-tech users to create and deploy NFT in PSP34 standard, a Polkadot-native standard for WASM-based NFTs.

**Acceptance Criteria**

- Build a frontend allowing non-tech users to connect their wallets, upload the images, and mint PSP34 NFT on Shiden Network.
- Metadata for the NFT should be stored on IPFS.
- Support Polkadot.js or Talisman wallets (browser extension).
- Deployed the contract using Polkadot.js API.
- Use OpenBrush to learn more about PSP34 and use the wizard to create the contract that this dApp will be deploying.

**Reward Tiers**

Up to $3000

- Contribution to the Astar ecosystem (25%)
- Originality, Creativity, and Innovation (25%)
- Technical Difficulty (25%)
- User Experience (25%)

## Resources
- Official documentation: [Here](https://docs.astar.network/)
- API documentation: [Here](https://docs.astar.network/docs/integrations/gas_api#overview)
- XCM documentation: [Here](https://docs.astar.network/docs/xcm/)
- Network details: [Here](https://docs.astar.network/docs/quickstart/endpoints/)
- All about dApp staking: [Here](https://docs.astar.network/docs/dapp-staking/)
- Example of AsterBase: [Here](https://docs.astar.network/docs/dapp-staking/for-devs/astarbase)
- Using precompiles: [Here](https://docs.astar.network/docs/EVM/precompiles)
- Developer hack support: [Join here](https://t.me/AstarHack)

Happy hacking!

**Comment by XingyuLi20** [comment]
How to submit it?

**Comment by fiexer** [comment]
You can submit it here!
We will review your bounty.

**Comment by CieloChiara** [comment]
Share a simple NFTViewer (PSP34) pull request URL.
(In the example, a pull request to the wasm-showcase-dapps repository)
Please refer to it as a reference case study if you like.

https://github.com/AstarNetwork/wasm-showcase-dapps/pull/26

* The pull request for the Issue is to the AstarBounties repository.

**Comment by fiexer** [comment]
Thanks a lot for your contribution @CieloChiara 
Our devs have already reviewed and approved your submission. 

We will soon reach out with the bounty reward earned.
